// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hebxqlbfqwjvnwcrtwim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlYnhxbGJmcXdqdm53Y3J0d2ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjA1MjMsImV4cCI6MjA3MzM5NjUyM30.PUiZ0m4FiV_5qAOTkhc8-V1sxbBOh4UAfxHiqpPKcBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});